
nnoremap('gD', function() vim.lsp.buf.declaration() end)
nnoremap('gd', function() vim.lsp.buf.definition() end)
nnoremap('gr', function() vim.lsp.buf.references() end)
nnoremap('K', function() vim.lsp.buf.hover() end)
nnoremap('gi', function() vim.lsp.buf.implementation() end)
nnoremap('<A-k>', function() vim.lsp.buf.signature_help() end)
nnoremap('<Leader>wa', function() vim.lsp.buf.add_workspace_folder() end)
nnoremap('<Leader>wr', function() vim.lsp.buf.remove_workspace_folder() end)
nnoremap('<Leader>wl', function() print(vim.inspect(vim.lsp.buf.list_workspace_folders())) end)
nnoremap('<Leader>D', function() vim.lsp.buf.type_definition() end)
nnoremap('<Leader>rn', function() vim.lsp.buf.rename() end)
nnoremap('<Leader>aa', function() vim.lsp.buf.code_action() end)
nnoremap('<Leader>fe', function() vim.lsp.diagnostic.show_line_diagnostics() end)
nnoremap('[d', function() vim.lsp.diagnostic.goto_prev() end)
nnoremap(']d', function() vim.lsp.diagnostic.goto_next() end)
nnoremap('<Leader>q', function() vim.lsp.diagnostic.set_loclist() end)
nnoremap('<leader>s', function() vim.lsp.buf.document_symbol() end)

nnoremap("<leader>li", ":LspInfo<CR>", "Language Server Info")
nnoremap("<leader>lr", ":LspRestart<CR>", "Restart LSP")
nnoremap("<leader>ls", ":LspStart<CR>", "Start LSP")
nnoremap("<leader>lS", ":LspStop<CR>", "Stop LSP")

